version: '3.7'

services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 8888:80/tcp
  db:
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    ports:
      - 1433:1433/tcp